"""initial

Revision ID: e150762f2ed1
Revises: 
Create Date: 2026-04-04 15:19:14.996289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e150762f2ed1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('call_attempts', sa.Integer(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('call_transcript', sa.Text(), nullable=True),
    sa.Column('call_summary', sa.Text(), nullable=True),
    sa.Column('vapi_call_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_opted_in', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_last_message_at', sa.DateTime(), nullable=True),
    sa.Column('whatsapp_sequence_step', sa.Integer(), nullable=True),
    sa.Column('meeting_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('calcom_booking_id', sa.String(length=255), nullable=True),
    sa.Column('preferred_time', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
