import { Lead, ActivityEvent } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Alice Smith",
    phone: "+14155552671",
    email: "alice@techcorp.com",
    company: "TechCorp Inc.",
    state: "hot",
    state_reason: "Very interested in the AI automation features. Wants to see a demo.",
    call_attempts: 1,
    last_called_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    call_transcript: "Agent: Hello, is this Alice?\nAlice: Yes, speaking.\nAgent: Hi Alice, I'm calling from AI Sales... [Transcript continues]",
    call_summary: "Alice was very receptive. She mentioned they are currently evaluating tools and our AI features stood out. Requested a demo for next week.",
    vapi_call_id: "vapi_12345",
    whatsapp_opted_in: true,
    whatsapp_last_message_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    whatsapp_sequence_step: 1,
    meeting_scheduled_at: null,
    calcom_booking_id: null,
    preferred_time: "Next Tuesday afternoon",
    source: "csv",
    notes: "Follow up with demo link.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "2",
    name: "Bob Jones",
    phone: "+447700900123",
    email: "bob.jones@globex.co.uk",
    company: "Globex Corp",
    state: "calling",
    state_reason: null,
    call_attempts: 1,
    last_called_at: new Date().toISOString(),
    call_transcript: null,
    call_summary: null,
    vapi_call_id: "vapi_67890",
    whatsapp_opted_in: false,
    whatsapp_last_message_at: null,
    whatsapp_sequence_step: 0,
    meeting_scheduled_at: null,
    calcom_booking_id: null,
    preferred_time: null,
    source: "json",
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Charlie Davis",
    phone: "+61491570156",
    email: "charlie@startup.io",
    company: "Startup.io",
    state: "booked",
    state_reason: "Ready to move forward, booked onboarding.",
    call_attempts: 2,
    last_called_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    call_transcript: "Agent: Hi Charlie...\nCharlie: Yes, let's book it.",
    call_summary: "Agreed to onboarding session.",
    vapi_call_id: "vapi_11223",
    whatsapp_opted_in: true,
    whatsapp_last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    whatsapp_sequence_step: 2,
    meeting_scheduled_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    calcom_booking_id: "cal_998877",
    preferred_time: "Mornings",
    source: "manual",
    notes: "VIP client",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "4",
    name: "Diana Prince",
    phone: "+12025550188",
    email: "diana@amazon.com",
    company: "Themyscira LLC",
    state: "warm",
    state_reason: "Interested but budget is tight until Q3.",
    call_attempts: 1,
    last_called_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    call_transcript: "Agent: Hello Diana...\nDiana: Sounds good but we have no budget right now.",
    call_summary: "Good fit, bad timing. Follow up in Q3.",
    vapi_call_id: "vapi_44556",
    whatsapp_opted_in: true,
    whatsapp_last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    whatsapp_sequence_step: 0,
    meeting_scheduled_at: null,
    calcom_booking_id: null,
    preferred_time: "Q3",
    source: "csv",
    notes: "Send case studies in the meantime.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "5",
    name: "Evan Wright",
    phone: "+13105550199",
    email: "evan@wright.net",
    company: "Wright Networks",
    state: "pending",
    state_reason: null,
    call_attempts: 0,
    last_called_at: null,
    call_transcript: null,
    call_summary: null,
    vapi_call_id: null,
    whatsapp_opted_in: false,
    whatsapp_last_message_at: null,
    whatsapp_sequence_step: 0,
    meeting_scheduled_at: null,
    calcom_booking_id: null,
    preferred_time: null,
    source: "json",
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "6",
    name: "Fiona Gallagher",
    phone: "+13125550144",
    email: "fiona@southside.com",
    company: "Southside Real Estate",
    state: "lost",
    state_reason: "Not interested, using competitor.",
    call_attempts: 1,
    last_called_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    call_transcript: "Agent: Hi Fiona...\nFiona: We already use XYZ Corp, please remove me from your list.",
    call_summary: "Hard no. Using competitor.",
    vapi_call_id: "vapi_99001",
    whatsapp_opted_in: false,
    whatsapp_last_message_at: null,
    whatsapp_sequence_step: 0,
    meeting_scheduled_at: null,
    calcom_booking_id: null,
    preferred_time: null,
    source: "csv",
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  }
];

export const mockActivities: ActivityEvent[] = [
  {
    id: "a1",
    lead_id: "2",
    lead_name: "Bob Jones",
    lead_phone: "+447700900123",
    type: "call_placed",
    description: "Call started for Bob Jones",
    timestamp: new Date().toISOString(),
  },
  {
    id: "a2",
    lead_id: "1",
    lead_name: "Alice Smith",
    lead_phone: "+14155552671",
    type: "whatsapp_sent",
    description: "WhatsApp message sent (Step 1)",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "a3",
    lead_id: "1",
    lead_name: "Alice Smith",
    lead_phone: "+14155552671",
    type: "call_completed",
    description: "Lead marked as hot",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "a4",
    lead_id: "5",
    lead_name: "Evan Wright",
    lead_phone: "+13105550199",
    type: "ingested",
    description: "Lead ingested via JSON",
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "a5",
    lead_id: "3",
    lead_name: "Charlie Davis",
    lead_phone: "+61491570156",
    type: "meeting_booked",
    description: "Meeting booked for Charlie Davis",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  }
];
